name: Image Rebuild and Upload on PR to Main

on:
  pull_request:
    branches: [ main ]
defaults:
    run:
        working-directory: app
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t weather-redix-group06:${{ github.sha }} .
      
      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ARM_ACR_PASSWORD }} | docker login ${{ secrets.ARM_ACR_LOGIN_SERVER }} -u ${{ secrets.ARM_ACR_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: docker tag weather-redix-group06:${{ github.sha }} ${{ secrets.ARM_ACR_LOGIN_SERVER }}/weather-redix-group06:${{ github.sha }}

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ARM_ACR_LOGIN_SERVER }}/weather-redix-group06:${{ github.sha }}