name: Docker Build

on:
  push:
    branches:
      - main
    # paths:
    #   - 'app/**'
defaults:
    run:
        working-directory: app
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t weather-redix-group06:${{ github.sha }} .
      