name: CD for Test And Prod
on:
  pull_request:
    branches: [ main ]
    paths:
        - 'app/**'
    
  push:
    branches: [ main ]
    paths:
        - 'app/**'

defaults:
    run:
        working-directory: app
jobs:
    
  build-image:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t weather-redix-group06:${{ github.sha }} .
      
      - name: Login to Azure Container Registry
        run: |
          echo ${{ secrets.ARM_ACR_PASSWORD }} | docker login ${{ secrets.ARM_ACR_LOGIN_SERVER }} -u ${{ secrets.ARM_ACR_USERNAME }} --password-stdin

      - name: Tag Docker image
        run: docker tag weather-redix-group06:${{ github.sha }} ${{ secrets.ARM_ACR_LOGIN_SERVER }}/weather-redix-group06:${{ github.sha }}

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ARM_ACR_LOGIN_SERVER }}/weather-redix-group06:${{ github.sha }}

      - uses: gliech/create-github-secret-action@v1.4.10          
        with:
            name: LATEST_TAG
            value: ${{ github.sha }}
            pa_token: ${{secrets.USER_ACTION_TOKEN_WORKFLOW}}

  deploy-test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build-image]
    name: 'Deploy to TEST'      
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Login to ACR
          run: |
            docker login ${{ secrets.ARM_ACR_LOGIN_SERVER }} -u ${{ secrets.ARM_ACR_USERNAME }} -p ${{ secrets.ARM_ACR_PASSWORD }}
    
        - name: Pull Docker image
          run: |
            docker pull ${{ secrets.ARM_ACR_LOGIN_SERVER }}/weather-redix-group06:${{ secrets.LATEST_TAG }}
    
        - name: Install Azure CLI
          run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
        - name: Install kubectl
          run: |
            sudo az aks install-cli
    
        - name: Set Credentials of AKS Cluster
          run: |
            kubectl create secret generic weather-api-key --from-literal=WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}
            kubectl create secret generic redis-host --from-literal=REDIS_HOST=${{ secrets.TEST_REDIS_HOST }}
            kubectl create secret generic redis-key --from-literal=REDIS_KEY=${{ secrets.TEST_REDIS_KEY }}
        
        - name: Deploy to AKS
          run: |
            echo "${{ secrets.ARM_KUBE_CONFIG_TEST }}" > kubeconfig.yaml
            export KUBECONFIG=kubeconfig.yaml
            kubectl apply -f app/k8s_deployment.yaml

        - name: Deploy to AKS
          run: |
            echo "${{ secrets.ARM_KUBE_CONFIG_TEST }}" > kubeconfig.yaml
            export KUBECONFIG=kubeconfig.yaml
            kubectl apply -f app/k8s_deployment.yaml
          
  deploy-prod:    
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: 'Deploy to PROD'
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Login to ACR
          run: |
            docker login ${{ secrets.ARM_ACR_LOGIN_SERVER }} -u ${{ secrets.ARM_ACR_USERNAME }} -p ${{ secrets.ARM_ACR_PASSWORD }}
    
        - name: Pull Docker image
          run: |
            docker pull ${{ secrets.ARM_ACR_LOGIN_SERVER }}/weather-redix-group06:${{ secrets.LATEST_TAG }}
    
        - name: Install Azure CLI
          run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
        - name: Install kubectl
          run: |
            sudo az aks install-cli
    
        - name: Set Credentials of AKS Cluster
          run: |
            kubectl create secret generic weather-api-key --from-literal=WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}
            kubectl create secret generic redis-host --from-literal=REDIS_HOST=${{ secrets.PROD_REDIS_HOST }}
            kubectl create secret generic redis-key --from-literal=REDIS_KEY=${{ secrets.PROD_REDIS_KEY }}
        
        - name: Deploy to AKS
          run: |
            echo "${{ secrets.ARM_KUBE_CONFIG_PROD }}" > kubeconfig.yaml
            export KUBECONFIG=kubeconfig.yaml
            kubectl apply -f app/k8s_deployment.yaml

        - name: Deploy to AKS
          run: |
            echo "${{ secrets.ARM_KUBE_CONFIG_PROD }}" > kubeconfig.yaml
            export KUBECONFIG=kubeconfig.yaml
            kubectl apply -f app/k8s_deployment.yaml
      