on:
  push:
    branches:
      - main

#Special permissions required for OIDC authentication
permissions:
    id-token: write
    contents: read
    pull-requests: write
  
#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
    ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
    ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

defaults:
    run:
        working-directory: infra/tf-backend  
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    # - name: Set Resource Group Name Secret
    #   run: echo "${{ steps.terraform_outputs.outputs.resource_group_name }}" >> $GITHUB_ENV

    # - name: Set Storage Account Name Secret
    #   run: echo "${{ steps.terraform_outputs.outputs.storage_account_name }}" >> $GITHUB_ENV

    # - name: Set Container Name Secret
    #   run: echo "${{ steps.terraform_outputs.outputs.container_name }}" >> $GITHUB_ENV

    # - name: Set Primary Access Key Secret
    #   run: echo "${{ steps.terraform_outputs.outputs.primary_access_key }}" >> $GITHUB_ENV
      
    # - name: Set ACR Login Server Secret
    #   run: echo "${{ steps.terraform_outputs.outputs.acr_login_server }}" >> $GITHUB_ENV

    # - name: Set ACR Username Secret
    #   run: echo "${{ steps.terraform_outputs.outputs.acr_username }}" >> $GITHUB_ENV

    # - name: Set ACR Password Secret
    #   run: echo "${{ steps.terraform_outputs.outputs.acr_password }}" >> $GITHUB_ENV

    - name: Export ARM_ACCESS_KEY
      run: echo "export ARM_ACCESS_KEY=${{ steps.terraform_outputs.outputs.primary_access_key }}" >> $GITHUB_ENV
        

    - name: Update ARM_ACCESS_KEY secret
      run: |
        
        SECRET_VALUE=$(echo -n "$ARM_ACCESS_KEY" | base64)
            
        curl \
            -X PUT \
            -H "Authorization: token ${{secrets.USER_ACTION_TOKEN_WORKFLOW}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/yuan0037/cst8918-final/actions/secrets/ARM_ACCESS_KEY \
            -d '{"encrypted_value":"'"$SECRET_VALUE"'","key_id":"'"ARM_ACCESS_KEY"'"}'

                     
    # - name: Upload Secrets
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: terraform-outputs
    #     path: terraform-outputs.txt