name: Backend CD
on:
  push:
    branches:
      - main
    paths:
      - 'infra/tf-backend/**'

#Special permissions required for OIDC authentication
permissions:
    id-token: write
    contents: read
    pull-requests: write
  
#These environment variables are used by the terraform azure provider to setup OIDD authenticate. 
env:
    ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
    ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
    ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"

defaults:
    run:
        working-directory: infra/tf-backend  
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve 
        
  # Refactored credential value retrieving using TerraForm output instead of getting from tfstate. 

    - name: Get Key
      id: get_key
      run: |
        echo "::set-output name=primary_access_key::$(terraform output -raw primary_access_key)"    
      
    
    - uses: 
        gliech/create-github-secret-action@v1.4.10
      with:
        name: ARM_ACCESS_KEY
        value: ${{steps.get_key.outputs.primary_access_key}}
        pa_token: ${{secrets.USER_ACTION_TOKEN_WORKFLOW}}

